### PR TITLE
Follow redirects for GitHub repos that were transferred

### PR DESCRIPTION
**Pull request by fridex**
## Related Issues and Dependencies

Related: https://github.com/thoth-station/prescriptions-refresh-job/issues/118
Related: https://github.com/thoth-station/prescriptions/pull/18663#issuecomment-1049092796

## This introduces a breaking change

- [x] No

### CODE REVIEW

**Comment by codificat** [comment]
/lgtm
thanks!
/approve

**Comment by fridex** [comment]
All green. Merging.

**Pull request merged**
