### PR TITLE
Fix organization names to string in prescription template

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Related to https://github.com/thoth-station/prescriptions/issues/22413

## This introduces a breaking change

- No

## This should yield a new module release

- No

## This Pull Request implements
Force string type in prescription template for organization, repository and package names.

### CODE REVIEW

**Review by fridex — COMMENTED** [review]
I'm not sure if this will pass pre-commit checks.

**Comment by codificat** [comment]
It did pass pre-commit checks
/approve

**Comment by fridex** [comment]
> It did pass pre-commit checks

I meant in the prescriptions repository. It has configured double quotes without possible redundancy. We might make these checks weaker then.

**Comment by codificat** [comment]
> I meant in the prescriptions repository.

Oh! Of course! :facepalm: my apologies

> It has configured double quotes without possible redundancy. We might make these checks weaker then.

You are right, the changes cause pre-commit's yamllint to fail when the quotes are applied to strings, e.g. (sample quick test):

```
yamllint.................................................................Failed
- hook id: yamllint
- exit code: 1

prescriptions/zo_/zope/gh_release_notes.yaml
  10:17     error    string value is redundantly quoted with double quotes  (quoted-strings)
  13:23     error    string value is redundantly quoted with double quotes  (quoted-strings)
  14:21     error    string value is redundantly quoted with double quotes  (quoted-strings)
```

I will send a revert for this.

**Pull request merged**
