### PR TITLE
Adapt Scorecards prescriptions to new dataset schema

### LINKED ISSUE #195: Update Scorecards handlers to `openssf.scorecardcron.scorecard-v2` schema
**Is your feature request related to a problem? Please describe.**
Scorecards prescriptions are not refreshed properly because the current handlers use an older Scorecards dataset version.
Related to https://github.com/thoth-station/prescriptions/issues/25118, https://github.com/thoth-station/core/issues/444 (among others)

**Describe the solution you'd like**
Adapt the current handlers to correspond to the schema of the new `openssf.scorecardcron.scorecard-v2` dataset.
Introduces a new scoring logic, justifications, project revisions and other data.

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Closes #195
Fixes https://github.com/thoth-station/prescriptions/issues/25118

## This introduces a breaking change

- No

## This should yield a new module release

- Yes

## This Pull Request implements

Adapt the Scorecards handler to the new `scorecards-v2` dataset schema.

### CODE REVIEW

**Comment by mayaCostantini** [comment]
cc @harshad16 @codificat ready for review

**Review by harshad16 — COMMENTED** [review]
/lgtm

thanks :100:

**Pull request merged**
