### PR TITLE
Add a general method to Prescriptions to generate prescription names

### PR DESCRIPTION
**Pull request by mayaCostantini**
## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Add a general method to generate prescription names and modify the files generating prescriptions accordingly.

### CODE REVIEW

**Review by fridex — APPROVED** [review]
Nice, looks good to me. Thanks Maya! 👍🏻

**Comment by mayaCostantini** [comment]
> Nice, looks good to me. Thanks Maya! 👍🏻

Thanks Frido! :100:

**Pull request merged**
